version: '3.5'
services:
  ohdsi_ehden_tools:
    build:
      context: ohdsi_ehden_tools
    ports:
      - "5641:5641"
    environment:
      ACHILLES_RUN: "1"
      # Add other environmental variables here to override entrypoint defaults
    networks:
      - demo-net
# NOTE THAT THIS IMAGE DOES NOT USE DOCKER SECRETS FOR DEPLOYMENT FLEXIBILITY
networks:
  demo-net:
    external:
      name: demo-net


