name: ehden_tools image

on:
  push:
    paths:
      - "ehden_tools/**"
      - ".github/workflows/ehden_tools-image.yml"
    branches:
      - master
      - main
      - OHDSI_EHDEN
    tags:
      - '*.*.*'

  # pull_request:
  #   branches: [ master ]
  # schedule:
  #   # NOTE: "*" is a special character in YAML, so quote it
  #   - cron:  '41 5 * * *'

env:
  CONTAINER: ehden_tools
  DH_ORG: edence
  GH_ORG: edencehealth
  PREFIX: ohdsi-

jobs:

  images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/login-action
      - name: Login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ env.GH_ORG }}/${{ env.PREFIX }}${{ env.CONTAINER }}
            ${{ env.DH_ORG }}/${{ env.PREFIX }}${{ env.CONTAINER }}
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.CONTAINER }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
          # linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
